<!DOCTYPE html>
<html>
<head>
    <title>IA: ChatGPT, Gemini y Bing</title>
    <style>
        .container {
            display: flex;           
            align-items: center;     
            margin-bottom: 20px;    
        }
        .container img {
            margin-right: 20px;      
        }
        h1 {
            font-size: 36px;        
            margin: 0;               
        }
        button {
            margin-top: 10px;        
            padding: 10px 15px;      
            font-size: 16px;         
            background-color: #4CAF50; 
            color: white;            
            border: none;            
            border-radius: 5px;      
            cursor: pointer;         
        }
        button:hover {
            background-color: #45a049; 
        }
    </style>
    <img src="IMAGENES/titulo_ia.png" alt="Logo de titulo_ia" width="1000" height="200" />
</head>
<body>
    <div class="container">
        <img src="IMAGENES/ChatGPT-Logo.png" alt="Logo de chatgpt" width="300" height="225" />
        <div>
            <h1>CHATGPT</h1>
            <p>
                <strong>Personalización Avanzada:</strong> ChatGPT está en un camino hacia una mayor personalización. En el futuro, podrá recordar interacciones anteriores, permitiendo conversaciones más fluidas y relevantes para el usuario, mejorando así la experiencia de interacción.
            </p>
            <p>
                <strong>Integración Multimodal:</strong> La próxima generación de ChatGPT podría incluir capacidades de procesamiento de imágenes y voz, lo que significaría que los usuarios podrían interactuar con la IA no solo mediante texto, sino también a través de imágenes y voz, ofreciendo una experiencia más rica y diversa.
            </p>
            <p>
                <strong>Aumento de la Creatividad:</strong> Se prevé que futuras versiones de ChatGPT sean aún más creativas, generando contenido no solo textual, sino también artístico, como música o arte visual, lo que podría revolucionar el campo de la creación artística y el entretenimiento.
            </p>
            <a href="https://openai.com/chatgpt/">
                <button>¡Descubre el Futuro de ChatGPT!</button>
            </a>
        </div>
    </div>

    <div class="container">
        <img src="IMAGENES/GEMINI.png" alt="Logo de gemini" width="225" height="250" />
        <div>
            <h1>GEMINI</h1>
            <p>
                <strong>Búsqueda Contextual y Predictiva:</strong> Gemini se proyecta como un motor de búsqueda que no solo responde preguntas, sino que también anticipa las necesidades del usuario, proporcionando resultados proactivos y relevantes basados en el contexto del usuario y sus preferencias anteriores.
            </p>
            <p>
                <strong>Interacción Visual y de Voz:</strong> Al igual que ChatGPT, Gemini está trabajando en capacidades multimodales. Los usuarios podrán realizar búsquedas utilizando imágenes o su voz, haciéndolo más accesible y práctico para todos.
            </p>
            <p>
                <strong>Mejoras en la Privacidad:</strong> Con un enfoque creciente en la privacidad de los datos, Gemini podría ofrecer opciones más robustas para que los usuarios controlen cómo se utilizan sus datos, garantizando una experiencia más segura y transparente.
            </p>
            <a href="https://gemini.google.com/?hl=es">
                <button>¡Explora el Poder de Gemini!</button>
            </a>
        </div>
    </div>

    <div class="container">
        <img src="IMAGENES/binglogo.jpg" alt="Logo de bing" width="225" height="325" />
        <div>
            <h1>BING</h1>
            <p>
                <strong>Integración de IA Conversacional:</strong> Bing está incorporando capacidades de IA conversacional que permitirán a los usuarios interactuar de manera más natural, similar a cómo lo hacen con ChatGPT. Esto podría cambiar radicalmente la forma en que los usuarios buscan información.
            </p>
            <p>
                <strong>Resultados Personalizados y Contextuales:</strong> Con el uso de inteligencia artificial, Bing se convertirá en un motor de búsqueda que no solo responde preguntas, sino que también comprende el contexto del usuario, ofreciendo resultados personalizados que se adaptan a las necesidades individuales de cada persona.
            </p>
            <p>
                <strong>Colaboraciones y Nuevas Funcionalidades:</strong> Bing está buscando colaborar con diversas plataformas y servicios para ofrecer una experiencia de búsqueda más integral, permitiendo a los usuarios acceder a múltiples fuentes de información y servicios directamente desde el motor de búsqueda.
            </p>
            <a href="https://www.bing.com/chat">
                <button>¡Adéntrate en el Mundo de Bing!</button>
            </a>
        </div>
    </div>
</body>
</html>
